# Generated by Django 5.0.4 on 2024-04-22 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frasedb',
            options={'verbose_name': 'Frase', 'verbose_name_plural': 'Frases'},
        ),
        migrations.RenameField(
            model_name='frasedb',
            old_name='Author_fk',
            new_name='Autor_fk',
        ),
    ]
